services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    command: bun run frontend:dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend:cached
      - ./config:/app/config:cached
      - ./package.json:/app/package.json:cached
      - ./bun.lockb:/app/bun.lockb:cached
      - frontend_deps:/app/frontend/node_modules
      - root_deps:/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    command: bun run server:dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server:cached
      - ./config:/app/config:cached
      - ./package.json:/app/package.json:cached
      - ./bun.lockb:/app/bun.lockb:cached
      - server_deps:/app/server/node_modules
      - root_deps:/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - ./server/.env

volumes:
  frontend_deps:
  server_deps:
  root_deps:
